### PR TITLE
Add tasks to get cluster metadata

### PR DESCRIPTION
**Pull request by rhcarvalho**
WIP note: implementation works, but we might want to put things into
functions, separate files, etc.

----------

https://issues.jboss.org/browse/RHMAP-9091
https://issues.jboss.org/browse/RHMAP-9536

### CODE REVIEW

**Comment by philbrookes** [comment]
I think we should have the version of the dump tool in this metadata too.

**Comment by rhcarvalho** [comment]
> I think we should have the version of the dump tool in this metadata too.

Yes, it is in the works.

**Comment by philbrookes** [comment]
:+1: LGTM

**Comment by rhcarvalho** [comment]
Moved code fetching openshift metadata to "openshift_metadata.go"

**Pull request merged**
